/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import edu.princeton.cs.algs4.Draw;

public class App {

    Draw draw;

    public App() {
        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000, 600);
        this.draw.setXscale(0, 1000);
        this.draw.setYscale(0, 600);
    }

    public static void main(String[] args) {
        App app = new App();
        Grade grade = new Grade();
        grade.desenhar(app.draw, 200, 100);
        app.draw.show();
    }
}
